PACKET_TYPE_COMMAND  = 0
PACKET_TYPE_RESPONSE = 1
PACKET_TYPE_MESSAGE  = 2

COMMAND_ESTOP  = 0
COMMAND_COLOR  = 1
COMMAND_MOVE   = 2
COMMAND_ARM    = 3

RESP_OK     = 0
RESP_STATUS = 1
RESP_COLOR  = 2
RESP_ARM    = 3

STATE_RUNNING = 0
STATE_STOPPED = 1

MAX_STR_LEN  = 32
PARAMS_COUNT = 16